import React from 'react';

type Styles = {
  [key: string]: React.CSSProperties;
};

export const styles: Styles = {
  // --- AuthScreen Styles ---
  authPage: {
    display: 'flex',
    height: '100%',
    width: '100%',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  authPanelLeft: {
    width: '50%',
    backgroundColor: '#007bff',
    color: 'white',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '40px',
    position: 'relative',
    overflow: 'hidden',
  },
  authPanelContent: {
    position: 'relative',
    zIndex: 2,
  },
  authBlob: {
    position: 'absolute',
    borderRadius: '50%',
    background: 'rgba(255, 255, 255, 0.1)',
    zIndex: 1,
  },
  authBlob1: {
    width: '300px',
    height: '300px',
    top: '-50px',
    left: '-100px',
    animation: 'moveBlob1 15s alternate infinite ease-in-out',
  },
  authBlob2: {
    width: '250px',
    height: '250px',
    bottom: '-80px',
    right: '-60px',
    animation: 'moveBlob2 18s alternate infinite ease-in-out',
  },
  authBlob3: {
    width: '150px',
    height: '150px',
    top: '40%',
    right: '20%',
    animation: 'moveBlob3 12s alternate infinite ease-in-out',
  },
  authTitle: {
    fontSize: '4rem',
    fontWeight: 700,
    marginBottom: '16px',
    textShadow: '0 2px 4px rgba(0,0,0,0.2)',
  },
  authSubtitle: {
    fontSize: '1.5rem',
    maxWidth: '400px',
    lineHeight: 1.5,
  },
  authPanelRight: {
    width: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f9fa',
  },
  authFormContainer: {
    width: '100%',
    maxWidth: '400px',
    padding: '2rem',
  },
  authTabs: {
    display: 'flex',
    marginBottom: '24px',
    borderBottom: '1px solid #e0e0e0',
  },
  authTab: {
    flex: 1,
    padding: '12px 0',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '18px',
    color: '#888',
    transition: 'color 0.2s, border-bottom-color 0.2s',
  },
  authTabActive: {
    flex: 1,
    padding: '12px 0',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '18px',
    color: '#007bff',
    fontWeight: 600,
    borderBottom: '3px solid #007bff',
  },
  authForm: {
    display: 'flex',
    flexDirection: 'column',
  },
  authMessage: {
    padding: '12px',
    borderRadius: '4px',
    marginBottom: '16px',
    textAlign: 'center',
    border: '1px solid transparent',
  },
  authMessageError: {
    backgroundColor: '#f8d7da',
    color: '#721c24',
    borderColor: '#f5c6cb',
  },
  authMessageSuccess: {
    backgroundColor: '#d4edda',
    color: '#155724',
    borderColor: '#c3e6cb',
  },
  authInput: {
    padding: '14px',
    fontSize: '16px',
    border: '1px solid #ccc',
    borderRadius: '8px',
    marginBottom: '16px',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  authButton: {
    padding: '14px',
    fontSize: '16px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s, transform 0.1s',
  },
  
  // --- Dashboard Layout ---
  dashboardLayout: {
    display: 'flex',
    height: '100vh',
    overflow: 'hidden',
    backgroundColor: '#f0f2f5',
  },
  sidebar: {
    width: '260px',
    backgroundColor: '#ffffff',
    borderRight: '1px solid #e9ecef',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    transition: 'width 0.3s ease, left 0.3s ease-in-out',
    flexShrink: 0,
  },
  sidebarOpen: {
    left: '0 !important',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  topBar: {
    height: '65px',
    borderBottom: '1px solid #e9ecef',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    backgroundColor: '#fff',
    flexShrink: 0,
  },
  topBarLeft: {
    display: 'flex',
    alignItems: 'center',
  },
  burgerButton: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    marginRight: '16px',
    color: '#495057',
    padding: '8px',
    borderRadius: '50%',
    display: 'none',
  },
  screenTitle: {
    fontSize: '22px',
    fontWeight: 600,
    color: '#212529',
  },
  screenContent: {
    flex: 1,
    overflowY: 'auto',
    backgroundColor: '#f0f2f5',
  },
  logo: {
    fontSize: '28px',
    fontWeight: 700,
    color: '#007bff',
    marginBottom: '32px',
    padding: '0 10px',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  navButton: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    padding: '12px 16px',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    color: '#495057',
    borderRadius: '8px',
    textAlign: 'left' as const,
    transition: 'background-color 0.2s, color 0.2s',
    fontWeight: 500,
  },
  navButtonActive: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    padding: '12px 16px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    borderRadius: '8px',
    textAlign: 'left' as const,
    transition: 'background-color 0.2s, color 0.2s',
    backgroundColor: '#e7f1ff',
    color: '#0056b3',
    fontWeight: 600,
  },
  navIcon: {
    marginRight: '12px',
    fontSize: '18px',
  },
  navChevron: {
    marginLeft: 'auto',
    transition: 'transform 0.3s',
  },
  navChevronOpen: {
    transform: 'rotate(180deg)',
  },
  aiToolsContainer: {
    overflow: 'hidden',
    transition: 'max-height 0.3s ease-in-out',
    paddingLeft: '20px',
  },
  
  // --- General Components ---
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e9ecef',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.02)',
    padding: '24px',
  },
  button: {
    padding: '10px 20px',
    fontSize: '15px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s, transform 0.1s',
  },
  buttonPrimary: {
    backgroundColor: '#007bff',
    color: 'white',
  },
  buttonSecondary: {
    backgroundColor: '#6c757d',
    color: 'white',
  },
  buttonDisabled: {
    padding: '14px',
    fontSize: '16px',
    backgroundColor: '#adb5bd',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    cursor: 'not-allowed',
    fontWeight: 600,
  },
  
  // --- Empty State ---
  emptyStateContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    padding: '40px',
    borderRadius: '12px',
    backgroundColor: '#f8f9fa',
    border: '2px dashed #dee2e6',
    height: '100%',
  },
  emptyStateIcon: {
    fontSize: '4rem',
    marginBottom: '16px',
  },
  emptyStateTitle: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: '#343a40',
    marginBottom: '8px',
  },
  emptyStateDescription: {
    fontSize: '1rem',
    color: '#6c757d',
    maxWidth: '400px',
    marginBottom: '24px',
  },
  emptyStateButton: {
    padding: '12px 24px',
    fontSize: '1rem',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s, transform 0.1s',
  },

  // --- AI Copilot FAB ---
  copilotFab: {
    position: 'fixed' as const,
    bottom: '30px',
    right: '30px',
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    backgroundColor: '#007bff',
    border: 'none',
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    cursor: 'pointer',
    zIndex: 1500,
    animation: 'pulse 2s infinite',
    transition: 'transform 0.3s ease',
  },

  // --- Content Plan Screen ---
  contentPlanContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    padding: '24px',
    gap: '24px',
  },
  contentPlanHeader: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  },
  contentPlanTitle: {
    fontSize: '24px',
    fontWeight: 600,
    color: '#212529',
  },
  calendarNav: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: '24px',
    gap: '8px',
  },
  calendarNavButton: {
    padding: '8px 12px',
    border: '1px solid #ced4da',
    borderRadius: '6px',
    background: '#fff',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#495057',
    transition: 'background-color 0.2s',
  },
  calendarContainer: {
    flex: 1,
    minHeight: 0,
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e9ecef',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gridTemplateRows: 'auto repeat(5, 1fr)',
    height: '100%',
    width: '100%',
  },
  calendarHeaderCell: {
    padding: '12px 8px',
    textAlign: 'center' as const,
    fontWeight: 600,
    color: '#6c757d',
    borderBottom: '1px solid #e9ecef',
    fontSize: '14px',
  },
  calendarDay: {
    borderBottom: '1px solid #e9ecef',
    borderRight: '1px solid #e9ecef',
    padding: '8px',
    position: 'relative' as const,
    transition: 'background-color 0.2s',
    display: 'flex',
    flexDirection: 'column',
  },
  calendarDayNotInMonth: {
    backgroundColor: '#f8f9fa',
    color: '#adb5bd',
  },
  calendarDayToday: {
    backgroundColor: '#e7f1ff',
  },
  calendarDayNumber: {
    fontWeight: 500,
    fontSize: '14px',
    marginBottom: '4px',
  },
  calendarPostsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    overflow: 'hidden',
    flex: 1,
  },
  postPill: {
    color: 'white',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    cursor: 'pointer',
    transition: 'filter 0.2s',
  },
  postPillMore: {
    color: '#495057',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 500,
    marginTop: '2px',
  },
};