import React from 'react';

export const baseCardStyles: React.CSSProperties = {
    backgroundColor: '#fff',
    padding: '24px',
    borderRadius: '12px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
    border: '1px solid #e9ecef',
    overflow: 'hidden',
};

export const styles: { [key: string]: React.CSSProperties } = {
    authPage: {
        display: 'flex',
        height: '100%',
        width: '100%',
        backgroundColor: '#fff',
    },
    authPanelLeft: {
        width: '50%',
        backgroundColor: '#007bff',
        color: '#fff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    authPanelRight: {
        width: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        backgroundColor: '#f8f9fa',
    },
    authBlob: {
        position: 'absolute',
        borderRadius: '50%',
        opacity: 0.15,
        filter: 'blur(40px)',
    },
    authBlob1: {
        width: '400px',
        height: '400px',
        backgroundColor: '#fff',
        top: '-100px',
        left: '-150px',
        animation: 'moveBlob1 20s infinite alternate',
    },
    authBlob2: {
        width: '300px',
        height: '300px',
        backgroundColor: '#ffc107',
        bottom: '-50px',
        right: '-100px',
        animation: 'moveBlob2 25s infinite alternate',
    },
    authBlob3: {
        width: '250px',
        height: '250px',
        backgroundColor: '#dc3545',
        bottom: '100px',
        left: '50px',
        animation: 'moveBlob3 15s infinite alternate',
    },
    authPanelContent: {
        textAlign: 'center',
        zIndex: 1,
    },
    authTitle: {
        fontSize: '4rem',
        fontWeight: 'bold',
        marginBottom: '1rem',
    },
    authSubtitle: {
        fontSize: '1.25rem',
        maxWidth: '400px',
    },
    authFormContainer: {
        width: '100%',
        maxWidth: '400px',
        padding: '0 20px',
    },
    authTabs: {
        display: 'flex',
        marginBottom: '2rem',
        borderBottom: '1px solid #dee2e6',
    },
    authTab: {
        flex: 1,
        padding: '1rem',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: '500',
        color: '#6c757d',
        position: 'relative',
    },
    authTabActive: {
        flex: 1,
        padding: '1rem',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: '600',
        color: '#007bff',
        borderBottom: '2px solid #007bff',
    },
    authForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    authInput: {
        padding: '0.9rem',
        fontSize: '1rem',
        border: '1px solid #ced4da',
        borderRadius: '8px',
        outline: 'none',
        transition: 'border-color 0.2s, box-shadow 0.2s',
    },
    authButton: {
        padding: '0.9rem',
        fontSize: '1rem',
        fontWeight: '600',
        color: '#fff',
        backgroundColor: '#007bff',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
    },
    authMessage: {
        padding: '1rem',
        borderRadius: '8px',
        marginBottom: '1rem',
        textAlign: 'center',
    },
    authMessageError: {
        backgroundColor: '#f8d7da',
        color: '#721c24',
        border: '1px solid #f5c6cb',
    },
    authMessageSuccess: {
        backgroundColor: '#d4edda',
        color: '#155724',
        border: '1px solid #c3e6cb',
    },
    dashboardLayout: {
        display: 'flex',
        height: '100%',
        width: '100%',
    },
    sidebar: {
        width: '260px',
        backgroundColor: '#fff',
        borderRight: '1px solid #e9ecef',
        padding: '24px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        transition: 'width 0.3s ease-in-out, left 0.3s ease-in-out',
    },
    sidebarOpen: {
        left: '0 !important',
    },
    logo: {
        fontSize: '2rem',
        fontWeight: 'bold',
        color: '#007bff',
        textAlign: 'center',
        marginBottom: '32px',
    },
    nav: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    navButton: {
        display: 'flex',
        alignItems: 'center',
        padding: '12px 16px',
        border: 'none',
        background: 'none',
        textAlign: 'left',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: '500',
        color: '#495057',
        borderRadius: '8px',
        transition: 'background-color 0.2s, color 0.2s',
        width: '100%',
    },
    navButtonActive: {
        display: 'flex',
        alignItems: 'center',
        padding: '12px 16px',
        border: 'none',
        textAlign: 'left',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: '600',
        borderRadius: '8px',
        backgroundColor: '#e7f1ff',
        color: '#007bff',
        width: '100%',
    },
    navIcon: {
        marginRight: '12px',
        fontSize: '1.2rem',
    },
    navChevron: {
        marginLeft: 'auto',
        transition: 'transform 0.2s',
    },
    navChevronOpen: {
        transform: 'rotate(90deg)',
    },
    aiToolsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        paddingLeft: '20px',
        overflow: 'hidden',
        transition: 'max-height 0.3s ease-in-out',
    },
    mainContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    topBar: {
        padding: '16px 32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottom: '1px solid #e9ecef',
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        backdropFilter: 'blur(8px)',
    },
    topBarLeft: {
        display: 'flex',
        alignItems: 'center',
    },
    burgerButton: {
        background: 'none',
        border: 'none',
        fontSize: '24px',
        cursor: 'pointer',
        marginRight: '16px',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '8px',
    },
    screenTitle: {
        fontSize: '1.75rem',
        fontWeight: '600',
        color: '#212529',
    },
    screenContent: {
        padding: '32px',
        overflowY: 'auto',
        height: '100%',
        backgroundColor: '#f8f9fa',
    },
    card: baseCardStyles,
    cardTitle: {
        margin: 0,
        marginBottom: '8px',
        fontSize: '1.25rem',
        fontWeight: '600',
    },
    cardSubtitle: {
        margin: 0,
        marginBottom: '20px',
        color: '#6c757d',
        fontSize: '0.9rem',
        lineHeight: 1.5,
    },
    contentPlanLayout: {
        display: 'grid',
        gridTemplateColumns: '350px 1fr',
        gap: '24px',
        height: '100%',
        overflow: 'hidden',
    },
    contentPlanControls: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        overflowY: 'auto',
    },
    planList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    planCard: {
        padding: '16px',
        border: '1px solid #e9ecef',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'transform 0.2s, box-shadow 0.2s',
        position: 'relative',
        paddingLeft: '24px',
        backgroundColor: '#fff',
    },
    planCardStatusIndicator: {
        position: 'absolute',
        left: '8px',
        top: '16px',
        width: '8px',
        height: '8px',
        borderRadius: '50%',
    },
    planCardDraggable: {
        cursor: 'grab',
    },
    planCardDragging: {
        opacity: 0.5,
        cursor: 'grabbing',
    },
    planCardTitle: {
        fontWeight: '600',
        fontSize: '1rem',
        marginBottom: '4px',
        display: 'block',
    },
    planCardBadge: {
        backgroundColor: '#e9ecef',
        color: '#495057',
        padding: '2px 8px',
        borderRadius: '12px',
        fontSize: '0.75rem',
        fontWeight: '500',
        display: 'inline-block',
        marginBottom: '8px',
    },
    planCardDescription: {
        fontSize: '0.9rem',
        color: '#6c757d',
        lineHeight: 1.5,
    },
    calendarContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
    },
    calendarHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
    },
    calendarTitle: {
        fontSize: '1.5rem',
        fontWeight: '600',
        textTransform: 'capitalize',
    },
    calendarNavButton: {
        background: 'none',
        border: '1px solid #ced4da',
        borderRadius: '50%',
        width: '36px',
        height: '36px',
        cursor: 'pointer',
        fontSize: '1rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'background-color 0.2s',
    },
    calendarGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(7, 1fr)',
        gridAutoRows: 'minmax(120px, 1fr)',
        gap: '4px',
        flex: 1,
    },
    calendarWeekDay: {
        textAlign: 'center',
        fontWeight: '600',
        color: '#6c757d',
        fontSize: '0.9rem',
        padding: '8px 0',
    },
    calendarDay: {
        border: '1px solid #e9ecef',
        borderRadius: '8px',
        padding: '8px',
        backgroundColor: '#fff',
        display: 'flex',
        flexDirection: 'column',
        transition: 'background-color 0.2s, border-color 0.2s',
        position: 'relative',
    },
    calendarDayDragOver: {
        backgroundColor: '#e7f1ff',
        border: '2px dashed #007bff',
    },
    calendarDayEmpty: {
        backgroundColor: '#f0f2f5',
        borderRadius: '8px',
    },
    calendarDayToday: {
        borderColor: '#007bff',
        backgroundColor: '#f0f8ff',
    },
    calendarDayNumber: {
        fontWeight: '600',
        marginBottom: '8px',
    },
    scheduledPostsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        overflow: 'hidden',
    },
    scheduledPostItem: {
        backgroundColor: '#e7f1ff',
        color: '#004085',
        padding: '4px 8px',
        borderRadius: '4px',
        fontSize: '0.8rem',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        cursor: 'pointer',
        borderLeft: '3px solid #007bff',
    },
    generatorLayout: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '24px',
        height: '100%',
    },
    generatorControls: {
        ...baseCardStyles,
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    generatorResult: {
        ...baseCardStyles,
        display: 'flex',
        flexDirection: 'column',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    label: {
        fontWeight: '600',
        fontSize: '1rem',
    },
    input: {
        padding: '12px',
        fontSize: '1rem',
        border: '1px solid #ced4da',
        borderRadius: '8px',
        outline: 'none',
        transition: 'border-color 0.2s, box-shadow 0.2s',
        width: '100%',
    },
    textarea: {
        padding: '12px',
        fontSize: '1rem',
        border: '1px solid #ced4da',
        borderRadius: '8px',
        outline: 'none',
        transition: 'border-color 0.2s, box-shadow 0.2s',
        width: '100%',
        minHeight: '80px',
        resize: 'vertical',
        fontFamily: 'inherit',
    },
    button: {
        padding: '12px 20px',
        fontSize: '1rem',
        fontWeight: '600',
        color: '#fff',
        backgroundColor: '#007bff',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
    },
    buttonDisabled: {
        padding: '12px 20px',
        fontSize: '1rem',
        fontWeight: '600',
        color: '#6c757d',
        backgroundColor: '#e9ecef',
        border: 'none',
        borderRadius: '8px',
        cursor: 'not-allowed',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
    },
    resultBox: {
        flex: 1,
        border: '1px solid #e9ecef',
        borderRadius: '8px',
        padding: '20px',
        backgroundColor: '#f8f9fa',
        overflowY: 'auto',
        lineHeight: 1.6,
    },
    loader: {
        border: '4px solid #f3f3f3',
        borderTop: '4px solid #007bff',
        borderRadius: '50%',
        width: '40px',
        height: '40px',
        animation: 'spin 1s linear infinite',
        margin: 'auto',
    },
    miniLoader: {
        border: '3px solid rgba(0, 123, 255, 0.3)',
        borderTop: '3px solid #007bff',
        borderRadius: '50%',
        width: '20px',
        height: '20px',
        animation: 'spin 1s linear infinite',
    },
    placeholderText: {
        color: '#6c757d',
        textAlign: 'center',
        margin: 'auto',
    },
    fileSelectionGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))',
        gap: '12px',
        maxHeight: '300px',
        overflowY: 'auto',
        padding: '4px',
    },
    fileSelectItem: {
        position: 'relative',
        height: '100px',
        borderRadius: '8px',
        border: '2px solid #e9ecef',
        cursor: 'pointer',
        overflow: 'hidden',
        backgroundColor: '#f8f9fa',
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'border-color 0.2s',
    },
    fileSelectItemActive: {
        borderColor: '#007bff',
    },
    fileSelectIcon: {
        fontSize: '2rem',
    },
    fileSelectOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        color: 'white',
        padding: '4px 8px',
        fontSize: '0.8rem',
        textAlign: 'center',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    fileSelectCheck: {
        position: 'absolute',
        top: '8px',
        right: '8px',
        width: '24px',
        height: '24px',
        borderRadius: '50%',
        backgroundColor: '#007bff',
        color: 'white',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
    },
    aspectRatioSelector: {
        display: 'flex',
        gap: '10px',
        flexWrap: 'wrap',
    },
    aspectRatioButton: {
        padding: '8px 16px',
        border: '1px solid #ced4da',
        background: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s, color 0.2s, border-color 0.2s',
    },
    aspectRatioButtonActive: {
        padding: '8px 16px',
        border: '1px solid #007bff',
        background: '#e7f1ff',
        color: '#007bff',
        borderRadius: '8px',
        cursor: 'pointer',
    },
    errorText: {
        color: '#dc3545',
        fontWeight: '500',
        textAlign: 'center',
    },
    imagePreviewContainer: {
        position: 'relative',
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    generatedImage: {
        maxWidth: '100%',
        maxHeight: '100%',
        borderRadius: '8px',
        objectFit: 'contain',
    },
    generatedVideo: {
        maxWidth: '100%',
        maxHeight: '100%',
        borderRadius: '8px',
        objectFit: 'contain',
    },
    imageActions: {
        position: 'absolute',
        bottom: '16px',
        left: '50%',
        transform: 'translateX(-50%)',
        display: 'flex',
        gap: '12px',
        backgroundColor: 'rgba(0,0,0,0.6)',
        padding: '8px 12px',
        borderRadius: '8px',
    },
    imageActionButton: {
        background: 'none',
        border: '1px solid #fff',
        color: '#fff',
        padding: '8px 16px',
        borderRadius: '6px',
        cursor: 'pointer',
        textDecoration: 'none',
        fontSize: '14px',
    },
    knowledgeBaseContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
    },
    dropzone: {
        border: '2px dashed #ced4da',
        borderRadius: '12px',
        padding: '40px',
        textAlign: 'center',
        color: '#6c757d',
        cursor: 'pointer',
        transition: 'border-color 0.2s, background-color 0.2s',
    },
    dropzoneActive: {
        borderColor: '#007bff',
        backgroundColor: '#f0f8ff',
    },
    uploadIcon: {
        fontSize: '3rem',
        display: 'block',
        marginBottom: '16px',
    },
    fileGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '20px',
    },
    fileCard: {
        position: 'relative',
        height: '180px',
        borderRadius: '12px',
        border: '1px solid #e9ecef',
        backgroundColor: '#f8f9fa',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundSize: 'cover',
        backgroundPosition: 'center',
    },
    fileCardIcon: {
        fontSize: '3.5rem',
    },
    fileCardOverlay: {
        position: 'absolute',
        bottom: '0',
        left: '0',
        right: '0',
        padding: '12px',
        backgroundColor: 'rgba(0,0,0,0.6)',
        color: '#fff',
        textAlign: 'center',
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    fileName: {
        fontWeight: '600',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        display: 'block',
    },
    fileTagsContainer: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '4px',
        justifyContent: 'center',
        maxHeight: '44px',
        overflow: 'hidden',
    },
    fileTag: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        color: '#fff',
        padding: '2px 6px',
        borderRadius: '4px',
        fontSize: '0.7rem',
    },
    fileCardAnalyzingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    deleteButton: {
        position: 'absolute',
        top: '8px',
        right: '8px',
        background: 'rgba(255, 0, 0, 0.5)',
        color: '#fff',
        border: 'none',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '1rem',
        opacity: 0,
        transition: 'opacity 0.2s, background-color 0.2s',
    },
    fileCardSkeleton: {
        height: '180px',
        backgroundColor: '#e9ecef',
        borderRadius: '12px',
        position: 'relative',
        overflow: 'hidden',
    },
    shimmer: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.5), transparent)',
        animation: 'shimmer 1.5s infinite',
    },
    settingsLayout: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '24px',
    },
    platformGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '16px',
    },
    platformCard: {
        display: 'flex',
        alignItems: 'center',
        padding: '16px',
        border: '2px solid #e9ecef',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'border-color 0.2s, background-color 0.2s',
    },
    platformCardActive: {
        borderColor: '#007bff',
        backgroundColor: '#f0f8ff',
    },
    platformIcon: {
        width: '32px',
        height: '32px',
        marginRight: '12px',
        objectFit: 'contain',
    },
    platformName: {
        fontWeight: '500',
    },
    teamInviteForm: {
        display: 'flex',
        gap: '12px',
        marginBottom: '20px',
    },
    inviteButton: {
        padding: '0 20px',
        fontSize: '1rem',
        fontWeight: '600',
        color: '#fff',
        backgroundColor: '#007bff',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
    },
    teamTable: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    teamTableTh: {
        textAlign: 'left',
        padding: '12px',
        borderBottom: '2px solid #e9ecef',
        color: '#6c757d',
        fontSize: '0.9rem',
        textTransform: 'uppercase',
    },
    teamTableTd: {
        padding: '12px',
        borderBottom: '1px solid #e9ecef',
    },
    teamRemoveButton: {
        background: 'none',
        border: 'none',
        color: '#dc3545',
        cursor: 'pointer',
        padding: 0,
    },
    emptyStateContainer: {
        textAlign: 'center',
        padding: '40px',
        backgroundColor: '#f8f9fa',
        borderRadius: '12px',
        border: '1px solid #e9ecef',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
    },
    emptyStateIcon: {
        fontSize: '3rem',
        marginBottom: '16px',
    },
    emptyStateTitle: {
        fontSize: '1.5rem',
        fontWeight: 600,
        marginBottom: '8px',
    },
    emptyStateDescription: {
        color: '#6c757d',
        maxWidth: '450px',
        margin: '0 auto 24px',
    },
    emptyStateButton: {
        padding: '12px 24px',
        fontSize: '1rem',
        fontWeight: 600,
        color: '#fff',
        backgroundColor: '#007bff',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
    },
    modalContent: {
        backgroundColor: 'white',
        padding: '32px',
        borderRadius: '12px',
        width: '90%',
        maxWidth: '700px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 10px 30px rgba(0,0,0,0.1)',
        position: 'relative',
    },
    drawerOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-end',
        zIndex: 1000,
    },
    drawerContent: {
        backgroundColor: 'white',
        width: '100%',
        maxWidth: '500px',
        height: '100%',
        maxHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '-10px 0 30px rgba(0,0,0,0.1)',
        position: 'relative',
        animation: 'slideInRight 0.3s ease-out',
        borderRadius: '12px 0 0 12px',
    },
    modalCloseButton: {
        position: 'absolute',
        top: '16px',
        right: '16px',
        background: 'none',
        border: 'none',
        fontSize: '24px',
        cursor: 'pointer',
        color: '#6c757d',
    },
    modalBody: {
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    modalHeader: {
        marginBottom: '16px',
        paddingBottom: '16px',
        borderBottom: '1px solid #e9ecef',
    },
    modalFooter: {
        marginTop: '24px',
        paddingTop: '16px',
        borderTop: '1px solid #e9ecef',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    statusBadge: {
        padding: '6px 12px',
        borderRadius: '16px',
        fontWeight: 600,
        display: 'inline-block',
    },
    deleteButtonFooter: {
        background: 'none',
        border: 'none',
        color: '#dc3545',
        fontWeight: 500,
        cursor: 'pointer',
    },
    campaignWizardResultSection: {
        marginTop: '16px',
        paddingTop: '16px',
        borderTop: '1px solid #e9ecef',
    },
    newCampaignButton: {
        padding: '8px 16px',
        fontSize: '0.9rem',
        background: 'linear-gradient(45deg, #007bff, #6610f2)',
        border: 'none',
    },
    copilotFab: {
        position: 'fixed',
        bottom: '32px',
        right: '32px',
        width: '64px',
        height: '64px',
        borderRadius: '50%',
        backgroundColor: '#007bff',
        color: 'white',
        border: 'none',
        boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
        fontSize: '2rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        transition: 'transform 0.2s, background-color 0.2s',
        zIndex: 1001,
    },
    // Styles for Content Adapter
    adapterSourceTabs: {
        display: 'flex',
        gap: '8px',
        borderBottom: '1px solid #dee2e6',
        marginBottom: '16px',
    },
    adapterSourceTab: {
        padding: '8px 16px',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: '500',
        color: '#6c757d',
        borderBottom: '2px solid transparent',
    },
    adapterSourceTabActive: {
        padding: '8px 16px',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: '600',
        color: '#007bff',
        borderBottom: '2px solid #007bff',
    },
    adapterPostList: {
        maxHeight: '200px',
        overflowY: 'auto',
        border: '1px solid #e9ecef',
        borderRadius: '8px',
    },
    adapterPostItem: {
        padding: '12px',
        borderBottom: '1px solid #e9ecef',
        cursor: 'pointer',
    },
    adapterPostItemActive: {
        backgroundColor: '#e7f1ff',
    },
    adapterResultGrid: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        height: '100%',
        overflowY: 'auto',
        paddingRight: '10px'
    },
    adapterResultCard: {
        padding: '20px',
        borderRadius: '12px',
        border: '1px solid #e9ecef',
        backgroundColor: '#fff',
        position: 'relative',
    },
    adapterResultHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '12px',
    },
    adapterResultTitle: {
        fontSize: '1.2rem',
        fontWeight: 600,
    },
    adapterCopyButton: {
        position: 'absolute',
        top: '16px',
        right: '16px',
        padding: '6px 12px',
        fontSize: '0.9rem',
        backgroundColor: '#f8f9fa',
        border: '1px solid #ced4da',
        color: '#495057',
    },
    modalTabs: {
        display: 'flex',
        borderBottom: '1px solid #dee2e6',
        marginBottom: '20px',
    },
    modalTab: {
        padding: '10px 20px',
        cursor: 'pointer',
        border: 'none',
        background: 'none',
        fontSize: '1rem',
        fontWeight: 500,
        color: '#6c757d',
        borderBottom: '2px solid transparent',
    },
    modalTabActive: {
        padding: '10px 20px',
        cursor: 'pointer',
        border: 'none',
        background: 'none',
        fontSize: '1rem',
        fontWeight: 600,
        color: '#007bff',
        borderBottom: '2px solid #007bff',
    },
    commentSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    commentList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    commentItem: {
        padding: '16px',
        borderRadius: '8px',
        backgroundColor: '#f8f9fa',
        border: '1px solid #e9ecef',
    },
    commentText: {
        marginBottom: '12px',
        lineHeight: 1.5,
    },
    replyButton: {
        padding: '6px 12px',
        fontSize: '0.9rem',
        backgroundColor: '#e7f1ff',
        color: '#004085',
        border: '1px solid #b8daff',
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
    },
    replyOptionsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        marginTop: '12px',
        borderTop: '1px solid #e9ecef',
        paddingTop: '12px',
    },
    replyOptionButton: {
        textAlign: 'left',
        padding: '10px',
        borderRadius: '6px',
        border: '1px solid #ced4da',
        background: '#fff',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
    },
    communityLayout: {
        display: 'grid',
        gridTemplateColumns: '280px 1fr',
        gap: '24px',
        height: '100%',
        overflow: 'hidden',
    },
    communitySidebar: {
        ...baseCardStyles,
        padding: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    communityFilterButton: {
        width: '100%',
        textAlign: 'left',
        padding: '10px 14px',
        border: 'none',
        background: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 500,
        fontSize: '1rem',
        transition: 'background-color 0.2s, color 0.2s',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    communityFilterButtonActive: {
        backgroundColor: '#e7f1ff',
        color: '#007bff',
        fontWeight: 600,
    },
    communityHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
    },
    autopilotToggle: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        cursor: 'pointer',
    },
    inboxFeed: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    inboxCard: {
        ...baseCardStyles,
        padding: '20px',
    },
    inboxCardHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
        marginBottom: '12px',
    },
    inboxCardAvatar: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        backgroundColor: '#e9ecef',
        flexShrink: 0,
    },
    inboxCardAuthor: {
        fontWeight: 600,
    },
    inboxCardMeta: {
        fontSize: '0.85rem',
        color: '#6c757d',
    },
    inboxCardAiTag: {
        marginLeft: 'auto',
        padding: '4px 10px',
        borderRadius: '16px',
        fontSize: '0.8rem',
        fontWeight: 500,
        backgroundColor: '#e7f1ff',
        color: '#004085',
        border: '1px solid #b8daff',
        flexShrink: 0,
    },
    inboxCardReplySection: {
        marginTop: '16px',
        borderTop: '1px solid #e9ecef',
        paddingTop: '16px',
    },
    inboxCardReplyTitle: {
        fontWeight: 600,
        marginBottom: '10px',
    },
    inboxCardReplyOption: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '12px',
        borderRadius: '8px',
        border: '1px solid #ced4da',
        marginBottom: '8px',
        backgroundColor: '#fff',
        transition: 'background-color 0.2s',
    },
    inboxCardReplyButton: {
        padding: '6px 12px',
        fontSize: '0.9rem',
    },
    forecastResultContainer: {
        marginTop: '12px',
        padding: '16px',
        borderRadius: '8px',
        border: '1px solid #e9ecef',
        backgroundColor: '#f8f9fa',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    forecastMetrics: {
        display: 'flex',
        justifyContent: 'space-around',
        textAlign: 'center',
    },
    forecastMetricItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    forecastMetricValue: {
        fontSize: '1.5rem',
        fontWeight: 'bold',
    },
    forecastMetricLabel: {
        fontSize: '0.8rem',
        color: '#6c757d',
    },
    forecastRecommendations: {
        borderTop: '1px solid #e9ecef',
        paddingTop: '12px',
    },
    toast: {
        backgroundColor: '#fff',
        color: '#333',
        padding: '16px',
        borderRadius: '8px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
        display: 'flex',
        alignItems: 'center',
        animation: 'toast-in-right 0.3s ease-out forwards',
        width: '350px',
        maxWidth: '90vw',
    },
    toastSuccess: {
        borderLeft: '5px solid #28a745',
    },
    toastError: {
        borderLeft: '5px solid #dc3545',
    },
    toastIcon: {
        fontSize: '24px',
        marginRight: '12px',
    },
    toastMessage: {
        fontWeight: 500,
        flex: 1,
    }
};

export const analyticsStyles: { [key: string]: React.CSSProperties } = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '16px',
    },
    dateRangePicker: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center',
    },
    dateRangeButton: {
        padding: '8px 16px',
        border: '1px solid #ced4da',
        background: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 500,
        transition: 'background-color 0.2s, color 0.2s, border-color 0.2s',
    },
    dateRangeButtonActive: {
        padding: '8px 16px',
        border: '1px solid #007bff',
        background: '#e7f1ff',
        color: '#007bff',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 600,
    },
    keyMetricsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '20px',
    },
    metricCard: {
        backgroundColor: '#fff',
        padding: '20px',
        borderRadius: '12px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
        border: '1px solid #e9ecef',
    },
    metricTitle: {
        margin: 0,
        fontSize: '14px',
        color: '#6c757d',
        marginBottom: '8px',
    },
    metricValue: {
        margin: 0,
        fontSize: '28px',
        fontWeight: '600',
        color: '#212529',
    },
    metricChange: {
        margin: 0,
        fontSize: '14px',
        fontWeight: '500',
    },
    mainGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gridTemplateRows: 'auto',
        gap: '24px',
        gridTemplateAreas: `
            "chart chart posts"
            "chart chart traffic"
        `,
    },
    largeCard: {
        gridColumn: 'span 2',
    },
    cardTitle: {
        marginBottom: '16px',
        fontSize: '18px',
        fontWeight: '600',
    },
    chartContainer: {
        height: '250px',
        width: '100%',
    },
    postList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        maxHeight: '300px',
        overflowY: 'auto',
    },
    postItem: {
        display: 'flex',
        alignItems: 'center',
        padding: '8px',
        borderRadius: '8px',
        transition: 'background-color 0.2s',
    },
    postPlatformIcon: {
        width: '20px',
        height: '20px',
        marginRight: '12px',
    },
    postTopic: {
        flex: 1,
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        fontSize: '14px',
    },
    postMetric: {
        fontWeight: '500',
        fontSize: '14px',
        marginLeft: '12px',
    },
    doughnutLayout: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '24px',
        marginTop: '20px',
    },
    doughnutChart: {
        width: '140px',
        height: '140px',
        borderRadius: '50%',
        position: 'relative',
    },
    doughnutLegend: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    legendItem: {
        display: 'flex',
        alignItems: 'center',
        fontSize: '14px',
    },
    legendMarker: {
        width: '12px',
        height: '12px',
        borderRadius: '50%',
        marginRight: '8px',
    },
    legendValue: {
        marginLeft: 'auto',
        fontWeight: '500',
        paddingLeft: '12px',
        color: '#6c757d',
    },
     // Styles for Competitor Analysis
    competitorAnalysisContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
    },
    competitorForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        padding: '24px',
        borderRadius: '12px',
        border: '1px solid #e9ecef',
        backgroundColor: '#fff',
    },
    competitorResults: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    competitorCard: {
        padding: '20px',
        borderRadius: '12px',
        border: '1px solid #e9ecef',
        backgroundColor: '#fff',
    },
    recommendationCard: {
        padding: '20px',
        borderRadius: '12px',
        border: '1px solid #007bff',
        backgroundColor: '#e7f1ff',
    },
    analysisList: {
        listStylePosition: 'inside',
        paddingLeft: '10px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    analysisTitle: {
        fontSize: '1.2rem',
        fontWeight: 600,
        marginBottom: '12px',
    },
};

export const copilotStyles: { [key: string]: React.CSSProperties } = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'space-between',
        textAlign: 'center',
        padding: '24px',
        backgroundColor: '#f8f9fa',
        borderRadius: '12px',
    },
    visualizer: {
        width: '150px',
        height: '150px',
        borderRadius: '50%',
        backgroundColor: '#007bff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
        fontSize: '4rem',
        transition: 'all 0.3s ease',
    },
    visualizerActive: {
        animation: 'pulse 2s infinite',
    },
    visualizerThinking: {
        background: 'linear-gradient(45deg, #007bff, #6610f2, #e83e8c, #fd7e14)',
        backgroundSize: '400% 400%',
        animation: 'thinking 3s ease infinite',
    },
    transcriptContainer: {
        flex: 1,
        width: '100%',
        overflowY: 'auto',
        margin: '24px 0',
        padding: '20px',
        border: '1px solid #e9ecef',
        borderRadius: '8px',
        backgroundColor: '#fff',
        textAlign: 'left',
    },
    transcriptEntry: {
        marginBottom: '12px',
        padding: '10px 14px',
        borderRadius: '8px',
        lineHeight: '1.5',
    },
    transcriptUser: {
        backgroundColor: '#e7f1ff',
        color: '#004085',
        textAlign: 'right',
    },
    transcriptModel: {
        backgroundColor: '#e9ecef',
        color: '#495057',
    },
    controls: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '12px',
    },
    statusText: {
        color: '#6c757d',
        fontWeight: 500,
        height: '24px',
    },
    copilotButton: {
        padding: '16px 32px',
        fontSize: '1.2rem',
        fontWeight: '600',
        color: '#fff',
        backgroundColor: '#007bff',
        border: 'none',
        borderRadius: '50px',
        cursor: 'pointer',
        transition: 'background-color 0.2s, transform 0.2s',
        minWidth: '200px',
    },
    copilotButtonStop: {
        backgroundColor: '#dc3545',
    }
};
