import React from 'react';

type Styles = {
  [key: string]: React.CSSProperties;
};

// Define reusable base styles as constants
const cardBase: React.CSSProperties = {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e9ecef',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.02)',
};

export const styles: Styles = {
  // --- AuthScreen Styles ---
  authPage: {
    display: 'flex',
    height: '100%',
    width: '100%',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  authPanelLeft: {
    width: '50%',
    backgroundColor: '#007bff',
    color: 'white',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '40px',
    position: 'relative',
    overflow: 'hidden',
  },
  authPanelContent: {
    position: 'relative',
    zIndex: 2,
  },
  authBlob: {
    position: 'absolute',
    borderRadius: '50%',
    background: 'rgba(255, 255, 255, 0.1)',
    zIndex: 1,
  },
  authBlob1: {
    width: '300px',
    height: '300px',
    top: '-50px',
    left: '-100px',
    animation: 'moveBlob1 15s alternate infinite ease-in-out',
  },
  authBlob2: {
    width: '250px',
    height: '250px',
    bottom: '-80px',
    right: '-60px',
    animation: 'moveBlob2 18s alternate infinite ease-in-out',
  },
  authBlob3: {
    width: '150px',
    height: '150px',
    top: '40%',
    right: '20%',
    animation: 'moveBlob3 12s alternate infinite ease-in-out',
  },
  authTitle: {
    fontSize: '4rem',
    fontWeight: 700,
    marginBottom: '16px',
    textShadow: '0 2px 4px rgba(0,0,0,0.2)',
  },
  authSubtitle: {
    fontSize: '1.5rem',
    maxWidth: '400px',
    lineHeight: 1.5,
  },
  authPanelRight: {
    width: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f9fa',
  },
  authFormContainer: {
    width: '100%',
    maxWidth: '400px',
    padding: '2rem',
  },
  authTabs: {
    display: 'flex',
    marginBottom: '24px',
    borderBottom: '1px solid #e0e0e0',
  },
  authTab: {
    flex: 1,
    padding: '12px 0',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '18px',
    color: '#888',
    transition: 'color 0.2s, border-bottom-color 0.2s',
  },
  authTabActive: {
    flex: 1,
    padding: '12px 0',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '18px',
    color: '#007bff',
    fontWeight: 600,
    borderBottom: '3px solid #007bff',
  },
  authForm: {
    display: 'flex',
    flexDirection: 'column',
  },
  authMessage: {
    padding: '12px',
    borderRadius: '4px',
    marginBottom: '16px',
    textAlign: 'center',
    border: '1px solid transparent',
  },
  authMessageError: {
    backgroundColor: '#f8d7da',
    color: '#721c24',
    borderColor: '#f5c6cb',
  },
  authMessageSuccess: {
    backgroundColor: '#d4edda',
    color: '#155724',
    borderColor: '#c3e6cb',
  },
  authInput: {
    padding: '14px',
    fontSize: '16px',
    border: '1px solid #ccc',
    borderRadius: '8px',
    marginBottom: '16px',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  authButton: {
    padding: '14px',
    fontSize: '16px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s, transform 0.1s',
  },
  
  // --- Dashboard Layout ---
  dashboardLayout: {
    display: 'flex',
    height: '100vh',
    overflow: 'hidden',
    backgroundColor: '#f0f2f5',
  },
  sidebar: {
    width: '260px',
    backgroundColor: '#ffffff',
    borderRight: '1px solid #e9ecef',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    transition: 'width 0.3s ease, left 0.3s ease-in-out',
    flexShrink: 0,
  },
  sidebarOpen: {
    left: '0 !important',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  topBar: {
    height: '65px',
    borderBottom: '1px solid #e9ecef',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    backgroundColor: '#fff',
    flexShrink: 0,
  },
  topBarLeft: {
    display: 'flex',
    alignItems: 'center',
  },
  topBarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    position: 'relative' as const,
  },
  burgerButton: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    marginRight: '16px',
    color: '#495057',
    padding: '8px',
    borderRadius: '50%',
    display: 'none',
  },
  screenTitle: {
    fontSize: '22px',
    fontWeight: 600,
    color: '#212529',
  },
  screenContent: {
    flex: 1,
    overflowY: 'auto',
    backgroundColor: '#f0f2f5',
  },
  logoButton: {
    fontSize: '28px',
    fontWeight: 700,
    color: '#007bff',
    marginBottom: '32px',
    padding: '0 10px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'left',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  navButton: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    padding: '12px 16px',
    minHeight: '50px', // Ensure min height but allow growing
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    color: '#495057',
    borderRadius: '8px',
    textAlign: 'left' as const,
    transition: 'background-color 0.2s, color 0.2s',
    fontWeight: 500,
  },
  navButtonActive: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    padding: '12px 16px',
    minHeight: '50px', // Ensure min height but allow growing
    border: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    borderRadius: '8px',
    textAlign: 'left' as const,
    transition: 'background-color 0.2s, color 0.2s',
    backgroundColor: '#e7f1ff',
    color: '#0056b3',
    fontWeight: 600,
  },
  navIcon: {
    marginRight: '12px',
    fontSize: '18px',
    width: '24px',
    height: '24px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
  },
  navChevron: {
    marginLeft: 'auto',
    transition: 'transform 0.3s',
  },
  navChevronOpen: {
    transform: 'rotate(180deg)',
  },
  aiToolsContainer: {
    overflow: 'hidden',
    transition: 'max-height 0.3s ease-in-out',
    paddingLeft: '20px',
  },
  
  // --- General Components ---
  card: {
    ...cardBase,
    padding: '24px',
  },
  button: {
    padding: '10px 20px',
    fontSize: '15px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s, transform 0.1s',
  },
  buttonPrimary: {
    backgroundColor: '#007bff',
    color: 'white',
  },
  buttonSecondary: {
    backgroundColor: '#6c757d',
    color: 'white',
  },
  buttonDanger: {
    backgroundColor: '#dc3545',
    color: 'white',
  },
  buttonDisabled: {
    padding: '14px',
    fontSize: '16px',
    backgroundColor: '#adb5bd',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    cursor: 'not-allowed',
    fontWeight: 600,
  },
  
  // --- Empty State ---
  emptyStateContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    padding: '40px',
    borderRadius: '12px',
    backgroundColor: '#f8f9fa',
    border: '2px dashed #dee2e6',
    height: '100%',
  },
  emptyStateIcon: {
    fontSize: '4rem',
    marginBottom: '16px',
  },
  emptyStateTitle: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: '#343a40',
    marginBottom: '8px',
  },
  emptyStateDescription: {
    fontSize: '1rem',
    color: '#6c757d',
    maxWidth: '400px',
    marginBottom: '24px',
  },
  emptyStateButton: {
    padding: '12px 24px',
    fontSize: '1rem',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s, transform 0.1s',
  },

  // --- AI Copilot FAB ---
  copilotFab: {
    position: 'fixed' as const,
    bottom: '30px',
    right: '30px',
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    backgroundColor: '#007bff',
    border: 'none',
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    cursor: 'pointer',
    zIndex: 1500,
    animation: 'pulse 2s infinite',
    transition: 'transform 0.3s ease',
  },

  // --- Content Plan Screen ---
  contentPlanLayout: {
    display: 'grid',
    gridTemplateColumns: '350px 1fr',
    gap: '24px',
    padding: '24px',
    height: '100%',
    overflow: 'hidden',
  },
  contentPlanControls: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e9ecef',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    overflowY: 'auto',
  },
  contentPlanCalendar: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  unscheduledPostsContainer: {
    marginTop: '16px',
    borderTop: '1px solid #e9ecef',
    paddingTop: '16px',
  },
  unscheduledPostsTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#495057',
    marginBottom: '12px',
  },
  unscheduledPostCard: {
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    padding: '12px',
    marginBottom: '8px',
    border: '1px solid #e9ecef',
    cursor: 'pointer',
    transition: 'box-shadow 0.2s, border-color 0.2s, transform 0.2s',
  },
  calendarNav: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginLeft: 'auto',
  },
  calendarNavButton: {
    padding: '8px 12px',
    border: '1px solid #ced4da',
    borderRadius: '6px',
    background: '#fff',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#495057',
    transition: 'background-color 0.2s',
  },
  calendarContainer: {
    flex: 1,
    minHeight: 0,
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e9ecef',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gridTemplateRows: 'auto repeat(5, 1fr)',
    height: '100%',
    width: '100%',
  },
  calendarHeaderCell: {
    padding: '12px 8px',
    textAlign: 'center' as const,
    fontWeight: 600,
    color: '#6c757d',
    borderBottom: '1px solid #e9ecef',
    fontSize: '14px',
  },
  calendarDay: {
    borderBottom: '1px solid #e9ecef',
    borderRight: '1px solid #e9ecef',
    padding: '8px',
    position: 'relative' as const,
    transition: 'background-color 0.2s',
    display: 'flex',
    flexDirection: 'column',
  },
  calendarDayDragOver: {
    backgroundColor: '#dcefff',
    border: '2px dashed #007bff',
  },
  calendarDayNotInMonth: {
    backgroundColor: '#f8f9fa',
    color: '#adb5bd',
  },
  calendarDayToday: {
    backgroundColor: '#e7f1ff',
  },
  calendarDayNumber: {
    fontWeight: 500,
    fontSize: '14px',
    marginBottom: '4px',
  },
  calendarPostsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    overflow: 'hidden',
    flex: 1,
  },
  postPill: {
    color: 'white',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    cursor: 'pointer',
    transition: 'filter 0.2s',
  },
  postPillMore: {
    color: '#495057',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 500,
    marginTop: '2px',
  },
  tooltipContainer: {
    position: 'fixed' as const,
    zIndex: 3000,
    pointerEvents: 'none' as const,
    transition: 'opacity 0.2s',
  },
  tooltipContent: {
      backgroundColor: 'rgba(20, 20, 20, 0.85)',
      color: 'white',
      padding: '10px 14px',
      borderRadius: '8px',
      fontSize: '14px',
      maxWidth: '350px',
      whiteSpace: 'pre-wrap' as const,
      lineHeight: 1.5,
      boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
  },
  // --- Modal Styles ---
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(17, 24, 39, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    backdropFilter: 'blur(4px)',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: '12px',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
    width: '90%',
    maxWidth: '600px',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    animation: 'slideInRight 0.3s ease-out forwards',
  },
  modalHeader: {
    padding: '16px 24px',
    borderBottom: '1px solid #e9ecef',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 600,
  },
  modalCloseButton: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    color: '#6c757d',
  },
  modalBody: {
    padding: '24px',
    overflowY: 'auto',
    flex: 1,
  },
  modalFooter: {
    padding: '16px 24px',
    borderTop: '1px solid #e9ecef',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
  },
  // --- Campaign Wizard Specific ---
  wizardStepIndicator: {
    marginBottom: '24px',
    display: 'flex',
    justifyContent: 'center',
    gap: '8px',
  },
  wizardStepDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#ced4da',
    transition: 'background-color 0.3s',
  },
  wizardStepDotActive: {
    backgroundColor: '#007bff',
  },
  wizardOptionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
  },
  wizardOptionCard: {
    border: '2px solid #e9ecef',
    borderRadius: '8px',
    padding: '20px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'border-color 0.2s, box-shadow 0.2s, transform 0.2s',
  },
  wizardOptionCardSelected: {
    borderColor: '#007bff',
    boxShadow: '0 0 0 3px rgba(0, 123, 255, 0.25)',
    transform: 'translateY(-2px)',
  },
  wizardOptionIcon: {
    fontSize: '32px',
    marginBottom: '12px',
  },
  wizardTextarea: {
    width: '100%',
    minHeight: '150px',
    padding: '12px',
    fontSize: '16px',
    border: '1px solid #ced4da',
    borderRadius: '8px',
    resize: 'vertical',
  },
  wizardSliderContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
  },
  wizardSliderLabel: {
    fontSize: '18px',
    fontWeight: 500,
  },
  wizardSlider: {
    width: '80%',
  },
  wizardLoadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '200px',
    gap: '16px',
  },
  spinner: {
    width: '48px',
    height: '48px',
    border: '5px solid #f3f3f3',
    borderTop: '5px solid #007bff',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },

  // --- Post Detail Modal Specific ---
  postDetailModalBody: {
    display: 'grid',
    gridTemplateColumns: '1fr 200px',
    gap: '24px',
  },
  postDetailContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  postDetailSidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  postDetailTextarea: {
    width: '100%',
    minHeight: '250px',
    padding: '12px',
    fontSize: '15px',
    border: '1px solid #ced4da',
    borderRadius: '8px',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: 1.6,
  },
  postDetailLabel: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#495057',
    marginBottom: '8px',
  },
  postDetailSelect: {
    width: '100%',
    padding: '10px',
    fontSize: '14px',
    border: '1px solid #ced4da',
    borderRadius: '8px',
    backgroundColor: '#fff',
  },
  postDetailDeleteButton: {
    marginRight: 'auto',
  },
  postDetailPublishButton: {
    width: '100%',
    marginTop: '16px',
    padding: '12px',
    fontSize: '16px',
    fontWeight: 600,
    backgroundColor: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.2s, transform 0.1s',
  },
  postDetailMediaSection: {
    marginTop: '20px',
  },
  postDetailMediaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(100px, 1fr))',
    gap: '10px',
    marginTop: '10px',
  },
  postDetailMediaThumbnailContainer: {
    position: 'relative' as const,
    width: '100px',
    height: '100px',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  postDetailMediaThumbnail: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
  },
  postDetailMediaRemoveBtn: {
    position: 'absolute' as const,
    top: '4px',
    right: '4px',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    color: 'white',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '16px',
    lineHeight: 1,
  },
  postDetailAddMediaBtn: {
    width: '100px',
    height: '100px',
    border: '2px dashed #ced4da',
    borderRadius: '8px',
    backgroundColor: '#f8f9fa',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#495057',
    fontSize: '14px',
    fontWeight: 500,
  },
  // --- A/B Test Display in Modal ---
  postDetailABTestTabsContainer: {
    display: 'flex',
    borderBottom: '1px solid #e9ecef',
    marginBottom: '16px',
  },
  postDetailABTestTab: {
    padding: '12px 16px',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    color: '#6c757d',
    fontWeight: 500,
    position: 'relative' as const,
    borderBottom: '3px solid transparent',
  },
  postDetailABTestTabActive: {
    padding: '12px 16px',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    color: '#007bff',
    fontWeight: 600,
    borderBottom: '3px solid #007bff',
  },
  postDetailABTestWinnerBadge: {
    marginLeft: '8px',
    fontSize: '16px',
  },
  postDetailABTestStatsCard: {
    ...cardBase,
    padding: '16px',
    textAlign: 'center' as const,
    backgroundColor: '#f8f9fa',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  
  // --- Knowledge Base / Media Library ---
  mediaLibraryLayout: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    padding: '24px',
  },
  mediaUploadZone: {
    border: '2px dashed #007bff',
    borderRadius: '12px',
    padding: '40px',
    textAlign: 'center',
    cursor: 'pointer',
    backgroundColor: '#e7f1ff',
    transition: 'background-color 0.2s',
  },
  mediaUploadZoneActive: {
    backgroundColor: '#d0e7ff',
  },
  mediaSearchInput: {
      width: '100%',
      padding: '12px 16px',
      fontSize: '16px',
      border: '1px solid #ced4da',
      borderRadius: '8px',
      transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  mediaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
    gap: '20px',
  },
  fileCard: {
    position: 'relative',
    aspectRatio: '1 / 1',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid #e9ecef',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  fileCardImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  fileCardOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: '8px',
    color: 'white',
    opacity: 0,
    transition: 'opacity 0.2s ease',
    pointerEvents: 'none',
  },
  analyzingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.8)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    color: '#343a40',
    zIndex: 10,
  },
  fileCardHover: {
    opacity: 1,
    pointerEvents: 'auto' as const,
  },
  fileCardName: {
    fontSize: '13px',
    fontWeight: 500,
    wordBreak: 'break-all',
  },
  fileCardTagsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
  },
  fileCardTag: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: '4px',
    padding: '2px 6px',
    fontSize: '10px',
  },
  fileCardDeleteButton: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    background: 'rgba(220, 53, 69, 0.8)',
    color: 'white',
    border: 'none',
    borderRadius: '50%',
    width: '28px',
    height: '28px',
    cursor: 'pointer',
    fontSize: '16px',
    lineHeight: '28px',
    zIndex: 5,
  },
  fileCardUploading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: '8px',
    backgroundColor: '#f8f9fa',
  },
  knowledgeSection: {
    marginTop: '24px',
    paddingTop: '20px',
    borderTop: '1px solid #e9ecef',
  },
  knowledgeActions: {
    display: 'flex',
    gap: '12px',
    marginBottom: '16px',
  },
  knowledgeList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  knowledgeItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '12px',
    borderRadius: '8px',
    backgroundColor: '#f8f9fa',
    border: '1px solid #e9ecef',
  },
  knowledgeItemIcon: {
    fontSize: '24px',
    flexShrink: 0,
  },
  knowledgeItemName: {
    flex: 1,
    fontSize: '14px',
    color: '#007bff',
    textDecoration: 'none',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
    // --- Media Picker Modal ---
  pickerSelectedOverlay: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 123, 255, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerSelectedCheckmark: {
    fontSize: '40px',
    color: 'white',
    textShadow: '0 1px 3px rgba(0,0,0,0.3)',
  },
  // --- Generator Screens ---
  generatorLayout: {
    display: 'grid',
    gridTemplateColumns: '400px 1fr',
    gap: '24px',
    padding: '24px',
    height: '100%',
    overflow: 'hidden',
  },
  generatorControls: {
    ...cardBase,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    overflowY: 'auto',
  },
  generatorResult: {
    ...cardBase,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflowY: 'auto',
    minHeight: '400px',
    padding: '24px',
  },
  imageGeneratorResultImage: {
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain' as const,
    borderRadius: '8px',
  },
  imageResultActions: {
      position: 'absolute' as const,
      bottom: '20px',
      left: '50%',
      transform: 'translateX(-50%)',
      display: 'flex',
      gap: '12px',
      backgroundColor: 'rgba(0,0,0,0.6)',
      padding: '10px 16px',
      borderRadius: '8px',
  },
  shimmerPlaceholder: {
      width: '100%',
      height: '100%',
      backgroundColor: '#e9ecef',
      position: 'relative',
      overflow: 'hidden',
  },
  shimmerEffect: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.4), transparent)',
      animation: 'shimmer 1.5s infinite',
  },
  generatorTextarea: {
      width: '100%',
      minHeight: '120px',
      padding: '12px',
      fontSize: '15px',
      border: '1px solid #ced4da',
      borderRadius: '8px',
      resize: 'vertical',
      fontFamily: 'inherit',
      lineHeight: 1.6,
  },
  generatorLabel: {
      fontSize: '14px',
      fontWeight: 600,
      color: '#495057',
      marginBottom: '8px',
  },
  generatorSelect: {
      width: '100%',
      padding: '10px',
      fontSize: '14px',
      border: '1px solid #ced4da',
      borderRadius: '8px',
      backgroundColor: '#fff',
  },
  // --- Prompt Library ---
  promptLibraryContainer: {
    border: '1px solid #e9ecef',
    borderRadius: '8px',
    backgroundColor: '#f8f9fa',
  },
  promptLibraryTabs: {
    display: 'flex',
    borderBottom: '1px solid #e9ecef',
  },
  promptLibraryTab: {
    flex: 1,
    padding: '10px',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#6c757d',
    fontWeight: 500,
  },
  promptLibraryTabActive: {
    backgroundColor: '#fff',
    color: '#007bff',
    fontWeight: 600,
  },
  promptLibraryContent: {
    padding: '12px',
    maxHeight: '150px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  promptLibraryItem: {
    padding: '8px 12px',
    borderRadius: '6px',
    fontSize: '13px',
    cursor: 'pointer',
    backgroundColor: '#fff',
    border: '1px solid #dee2e6',
    transition: 'background-color 0.2s, border-color 0.2s',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  // --- Analytics Screen ---
  analyticsLayout: {
      display: 'flex',
      flexDirection: 'column',
      gap: '24px',
      padding: '24px',
  },
  analyticsHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
  },
  analyticsControls: {
      display: 'flex',
      alignItems: 'center',
      gap: '24px',
      flexWrap: 'wrap',
  },
  periodButtonGroup: {
      display: 'flex',
      border: '1px solid #ced4da',
      borderRadius: '8px',
      overflow: 'hidden',
  },
  periodButton: {
      padding: '8px 16px',
      border: 'none',
      background: '#fff',
      cursor: 'pointer',
      fontSize: '14px',
      color: '#495057',
      transition: 'background-color 0.2s',
      borderRight: '1px solid #ced4da',
  },
  periodButtonActive: {
      padding: '8px 16px',
      border: 'none',
      cursor: 'pointer',
      fontSize: '14px',
      backgroundColor: '#007bff',
      color: 'white',
      fontWeight: 600,
  },
  compareCheckboxContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
  },
  compareCheckbox: {
      width: '18px',
      height: '18px',
      cursor: 'pointer',
  },
  analyticsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
      gap: '24px',
  },
  statCard: {
      ...cardBase,
      padding: '24px',
      display: 'flex',
      alignItems: 'center',
      gap: '20px',
  },
  statCardIcon: {
      fontSize: '36px',
      backgroundColor: '#e7f1ff',
      color: '#0056b3',
      borderRadius: '50%',
      width: '60px',
      height: '60px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
  },
  statCardValueContainer: {
      display: 'flex',
      alignItems: 'baseline',
      gap: '8px',
  },
  statCardValue: {
      fontSize: '28px',
      fontWeight: 700,
      color: '#212529',
  },
  statCardLabel: {
      fontSize: '14px',
      color: '#6c757d',
  },
  statCardChange: {
      fontSize: '14px',
      fontWeight: 600,
      padding: '2px 6px',
      borderRadius: '6px',
  },
  statCardChangePositive: {
      backgroundColor: '#d4edda',
      color: '#155724',
  },
  statCardChangeNegative: {
      backgroundColor: '#f8d7da',
      color: '#721c24',
  },
  analyticsSectionTitle: {
      fontSize: '18px',
      fontWeight: 600,
      marginBottom: '20px',
  },
  platformPerformanceList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
  },
  platformItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '16px',
  },
  platformProgressBarContainer: {
      width: '100%',
      height: '8px',
      backgroundColor: '#e9ecef',
      borderRadius: '4px',
      display: 'flex',
      overflow: 'hidden',
  },
  platformProgressBar: {
      height: '100%',
      transition: 'width 0.5s ease-in-out',
  },
  topPostsList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
  },
  topPostItem: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '12px 0',
      borderBottom: '1px solid #f1f3f5',
  },
  // --- Settings Screen ---
  settingsLayout: {
      padding: '24px',
      maxWidth: '900px',
      margin: '0 auto',
      display: 'flex',
      flexDirection: 'column',
      gap: '24px',
  },
  settingsSectionCard: {
      ...cardBase,
      padding: '24px',
  },
  settingsTabsContainer: {
      display: 'flex',
      borderBottom: '1px solid #e9ecef',
      padding: '0 24px',
  },
  settingsTabButton: {
      padding: '16px 20px',
      border: 'none',
      background: 'none',
      cursor: 'pointer',
      fontSize: '16px',
      color: '#6c757d',
      fontWeight: 500,
      borderBottom: '3px solid transparent',
      transition: 'color 0.2s, border-color 0.2s',
      position: 'relative',
  },
  settingsTabButtonActive: {
      padding: '16px 20px',
      border: 'none',
      background: 'none',
      cursor: 'pointer',
      fontSize: '16px',
      color: '#007bff',
      fontWeight: 600,
      borderBottom: '3px solid #007bff',
      position: 'relative',
  },
  settingsSectionTitle: {
      fontSize: '20px',
      fontWeight: 600,
      marginBottom: '20px',
      color: '#343a40',
  },
  teamList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
  },
  teamMemberItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '16px',
      padding: '12px',
      borderRadius: '8px',
      backgroundColor: '#f8f9fa',
      border: '1px solid #e9ecef',
  },
  teamMemberAvatar: {
      width: '40px',
      height: '40px',
      borderRadius: '50%',
      color: 'white',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontWeight: 600,
      fontSize: '16px',
      flexShrink: 0,
  },
  teamMemberInfo: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
  },
  teamMemberEmail: {
      fontWeight: 500,
      color: '#212529',
  },
  teamMemberRole: {
      fontSize: '14px',
      color: '#6c757d',
  },
  teamRoleSelect: {
    fontSize: '14px',
    color: '#495057',
    border: '1px solid #e9ecef',
    borderRadius: '6px',
    padding: '4px 8px',
    backgroundColor: '#fff',
    cursor: 'pointer',
    marginTop: '4px',
  },
  teamRemoveButton: {
      background: 'none',
      border: 'none',
      color: '#dc3545',
      cursor: 'pointer',
      fontSize: '14px',
      fontWeight: 500,
      padding: '4px 8px',
  },
  inviteForm: {
      marginTop: '24px',
      paddingTop: '20px',
      borderTop: '1px solid #e9ecef',
      display: 'flex',
      gap: '12px',
      alignItems: 'center',
  },
  inviteInput: {
      flex: 1,
      padding: '10px 14px',
      fontSize: '14px',
      border: '1px solid #ced4da',
      borderRadius: '8px',
      transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  inviteButton: {
      padding: '10px 20px',
      fontSize: '14px',
      fontWeight: 600,
      backgroundColor: '#007bff',
      color: 'white',
      border: 'none',
      cursor: 'pointer',
      transition: 'background-color 0.2s',
      borderRadius: '8px',
  },
  settingsForm: {
      display: 'flex',
      flexDirection: 'column',
      gap: '24px',
  },
  settingsFormGroup: {
      display: 'flex',
      flexDirection: 'column',
  },
  settingsLabel: {
      fontSize: '14px',
      fontWeight: 600,
      color: '#495057',
      marginBottom: '8px',
  },
  settingsTextarea: {
      width: '100%',
      padding: '12px',
      fontSize: '14px',
      border: '1px solid #ced4da',
      borderRadius: '8px',
      resize: 'vertical',
      fontFamily: 'inherit',
      lineHeight: 1.6,
  },
  settingsSaveButtonContainer: {
      display: 'flex',
      justifyContent: 'flex-end',
      marginTop: '16px',
  },
  // --- New styles for Connected Accounts ---
  platformGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '16px',
  },
  platformCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    borderRadius: '8px',
    border: '1px solid #e9ecef',
    backgroundColor: '#f8f9fa',
  },
  platformIcon: {
    fontSize: '28px',
    width: '40px',
    textAlign: 'center' as const,
  },
  platformInfo: {
    flex: 1,
  },
  platformName: {
    fontWeight: 600,
    fontSize: '16px',
  },
  platformStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '14px',
  },
  statusIndicator: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
  },
  statusConnected: {
    color: '#28a745',
  },
  statusDisconnected: {
    color: '#6c757d',
  },
  platformButton: {
    padding: '8px 16px',
    fontSize: '14px',
  },
  // --- Community Screen ---
  communityLayout: {
    display: 'grid',
    gridTemplateColumns: '400px 1fr',
    gap: '24px',
    padding: '24px',
    height: '100%',
    overflow: 'hidden',
  },
  postListColumn: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e9ecef',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  postListHeader: {
    padding: '16px',
    borderBottom: '1px solid #e9ecef',
    fontWeight: 600,
    fontSize: '18px',
    flexShrink: 0,
  },
  postList: {
    overflowY: 'auto',
    flex: 1,
  },
  postListItem: {
    padding: '16px',
    borderBottom: '1px solid #e9ecef',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  postListItemActive: {
    backgroundColor: '#e7f1ff',
    borderLeft: '4px solid #007bff',
    paddingLeft: '12px',
  },
  postListItemContent: {
    fontSize: '14px',
    color: '#495057',
    marginBottom: '8px',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  postListItemMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '12px',
    color: '#6c757d',
  },
  unansweredBadge: {
    backgroundColor: '#dc3545',
    color: 'white',
    borderRadius: '50%',
    width: '22px',
    height: '22px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    fontSize: '12px',
  },
  commentFeedColumn: {
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
    gap: '16px',
    paddingRight: '8px',
  },
  commentCard: {
    ...cardBase,
    padding: '20px',
  },
  commentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  commentAuthor: {
    fontWeight: 600,
  },
  commentTimestamp: {
    fontSize: '12px',
    color: '#6c757d',
  },
  commentStatusIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 500,
    textTransform: 'capitalize' as const,
  },
  commentStatusDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
  },
  commentBody: {
    lineHeight: 1.6,
    marginBottom: '16px',
  },
  commentActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '12px',
    borderTop: '1px solid #f1f3f5',
    paddingTop: '16px',
    marginTop: '16px',
  },
  commentActionButton: {
    background: 'none',
    border: '1px solid #ced4da',
    borderRadius: '6px',
    padding: '6px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    transition: 'background-color 0.2s, border-color 0.2s',
  },
  aiReplyButton: {
    marginRight: 'auto',
    background: '#e7f1ff',
    border: '1px solid #b8d6ff',
    color: '#0056b3',
    borderRadius: '6px',
    padding: '6px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    transition: 'background-color 0.2s',
  },
  aiReplyContainer: {
    marginTop: '16px',
    padding: '12px',
    backgroundColor: '#f8f9fa',
    border: '1px solid #e9ecef',
    borderRadius: '8px',
  },
  aiReplyTextarea: {
    width: '100%',
    padding: '8px',
    fontSize: '14px',
    border: '1px solid #ced4da',
    borderRadius: '6px',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: 1.5,
    minHeight: '80px',
  },
  aiReplyActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
    marginTop: '8px',
  },
  spamCommentCard: {
    backgroundColor: '#fffbe6',
    borderColor: '#ffe58f',
  },
  spamCommentText: {
    filter: 'blur(2px)',
    transition: 'filter 0.2s ease-in-out',
  },
  spamCommentActions: {
    justifyContent: 'center',
  },
  // --- Video Generator ---
  videoGeneratorImageUpload: {
      border: '2px dashed #ced4da',
      borderRadius: '8px',
      padding: '20px',
      textAlign: 'center',
      cursor: 'pointer',
      backgroundColor: '#f8f9fa',
      transition: 'background-color 0.2s, border-color 0.2s',
      minHeight: '120px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
  },
  videoGeneratorImageUploadActive: {
      backgroundColor: '#e9ecef',
      borderColor: '#007bff',
  },
  videoGeneratorImagePreviewContainer: {
      position: 'relative' as const,
      width: '100%',
      paddingTop: '56.25%', /* 16:9 Aspect Ratio */
      borderRadius: '8px',
      overflow: 'hidden',
      backgroundColor: '#e9ecef',
  },
  videoGeneratorImagePreview: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
  },
  videoGeneratorRemoveImageBtn: {
      position: 'absolute' as const,
      top: '8px',
      right: '8px',
      background: 'rgba(0,0,0,0.6)',
      color: 'white',
      border: 'none',
      borderRadius: '50%',
      width: '28px',
      height: '28px',
      cursor: 'pointer',
      fontSize: '16px',
  },
  videoGeneratorResultVideo: {
      maxWidth: '100%',
      maxHeight: '100%',
      borderRadius: '8px',
      border: '1px solid #dee2e6',
      backgroundColor: 'black',
  },
  // --- Strategy Generator ---
  strategyResultContent: {
      width: '100%',
      padding: '24px',
      lineHeight: 1.7,
      color: '#343a40',
      textAlign: 'left',
  },
  strategyResultTitle: {
      fontSize: '24px',
      fontWeight: 700,
      color: '#212529',
      marginBottom: '24px',
      paddingBottom: '16px',
      borderBottom: '1px solid #e9ecef',
  },
  strategyResultSectionTitle: {
      fontSize: '18px',
      fontWeight: 600,
      color: '#0056b3',
      marginTop: '24px',
      marginBottom: '12px',
  },
  strategyResultList: {
      listStyleType: '"- "',
      paddingLeft: '20px',
  },
  strategyResultListItem: {
      marginBottom: '8px',
  },
  strategyExportButton: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    zIndex: 10,
  },
  // --- Trend Spotter Screen ---
  trendSpotterLayout: {
      padding: '24px',
      maxWidth: '1000px',
      margin: '0 auto',
      display: 'flex',
      flexDirection: 'column',
      gap: '24px',
  },
  trendSearchContainer: {
      ...cardBase,
      padding: '24px',
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
  },
  trendSearchInput: {
      flex: 1,
      padding: '12px 16px',
      fontSize: '16px',
      border: '1px solid #ced4da',
      borderRadius: '8px',
      transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  trendExamplePill: {
      background: '#e9ecef',
      border: '1px solid #dee2e6',
      borderRadius: '16px',
      padding: '6px 12px',
      fontSize: '14px',
      cursor: 'pointer',
      color: '#495057',
      transition: 'background-color 0.2s, border-color 0.2s',
  },
  historyPill: {
      background: '#e7f1ff',
      border: '1px solid #b8d6ff',
      borderRadius: '16px',
      padding: '6px 12px',
      fontSize: '14px',
      cursor: 'pointer',
      color: '#0056b3',
      transition: 'background-color 0.2s, border-color 0.2s',
  },
  trendResultsContainer: {
      ...cardBase,
      padding: '32px',
      minHeight: '300px',
  },
  trendResultGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '24px',
      gridAutoFlow: 'dense',
  },
  trendResultCard: {
      backgroundColor: '#f8f9fa',
      borderRadius: '12px',
      padding: '20px',
      border: '1px solid #e9ecef',
      gridColumn: 'span 1',
  },
  trendCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '16px',
  },
  trendCardIcon: {
    fontSize: '24px',
  },
  trendCardTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#343a40',
  },
  trendCardList: {
    paddingLeft: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    fontSize: '14px',
    color: '#495057',
  },
  hashtagContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  hashtagPill: {
    backgroundColor: '#e9ecef',
    borderRadius: '16px',
    padding: '4px 10px',
    fontSize: '13px',
    color: '#495057',
  },
  trendSourcesContainer: {
      marginTop: '32px',
      paddingTop: '20px',
      borderTop: '2px solid #e9ecef',
  },
  trendSourcesTitle: {
      fontSize: '16px',
      fontWeight: 600,
      color: '#495057',
      marginBottom: '12px',
  },
  trendSourceLinkWithFavicon: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px',
    borderRadius: '8px',
    textDecoration: 'none',
    color: '#0056b3',
    backgroundColor: '#f8f9fa',
    border: '1px solid #e9ecef',
    marginBottom: '8px',
    transition: 'background-color 0.2s, border-color 0.2s',
  },
  trendSourceFavicon: {
    width: '24px',
    height: '24px',
    flexShrink: 0,
  },
  skeletonText: {
    height: '20px',
    backgroundColor: '#e9ecef',
    borderRadius: '4px',
    marginBottom: '10px',
  },
  skeletonTextMedium: {
    height: '24px',
    backgroundColor: '#e0e0e0',
    borderRadius: '4px',
    marginBottom: '16px',
    width: '60%',
  },
    // --- Image Editor Screen ---
  imageEditorLayout: {
    display: 'grid',
    gridTemplateColumns: '400px 1fr',
    gap: '24px',
    padding: '24px',
    height: '100%',
    overflow: 'hidden',
  },
  imageEditorControls: {
    ...cardBase,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  imageEditorCanvas: {
    ...cardBase,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    minHeight: '400px',
    padding: '16px',
  },
  imageEditorImage: {
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain' as const,
    borderRadius: '8px',
  },
  imageEditorImageUpload: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
  },
  imageEditorDropzone: {
    border: '2px dashed #ced4da',
    borderRadius: '8px',
    padding: '40px 20px',
    textAlign: 'center' as const,
    cursor: 'pointer',
    backgroundColor: '#f8f9fa',
    transition: 'background-color 0.2s, border-color 0.2s',
  },
  imageEditorOriginalPreview: {
    border: '1px solid #e9ecef',
    borderRadius: '8px',
    padding: '8px',
  },
    // --- Content Adapter Screen ---
  contentAdapterLayout: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '24px',
    padding: '24px',
    height: '100%',
    overflow: 'hidden',
  },
  contentAdapterPanel: {
    ...cardBase,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    overflowY: 'auto',
  },
  contentAdapterTextarea: {
    width: '100%',
    flex: 1, // Take up available space
    padding: '12px',
    fontSize: '15px',
    border: '1px solid #ced4da',
    borderRadius: '8px',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: 1.6,
  },
  contentAdapterResult: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    border: '1px solid #e9ecef',
    padding: '12px',
    whiteSpace: 'pre-wrap',
    lineHeight: 1.6,
    overflowY: 'auto',
    position: 'relative',
  },
  contentAdapterCopyButton: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    padding: '6px 10px',
    fontSize: '13px',
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  // --- Notifications ---
  notificationBell: {
    position: 'relative' as const,
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    color: '#495057',
    padding: '8px',
    borderRadius: '50%',
  },
  notificationBadge: {
    position: 'absolute' as const,
    top: '4px',
    right: '4px',
    backgroundColor: '#dc3545',
    color: 'white',
    borderRadius: '50%',
    width: '18px',
    height: '18px',
    fontSize: '11px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px solid white',
  },
  notificationPanel: {
    position: 'absolute' as const,
    top: '55px',
    right: '0',
    width: '350px',
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    zIndex: 1000,
    border: '1px solid #e9ecef',
    overflow: 'hidden',
  },
  notificationPanelHeader: {
    padding: '12px 16px',
    borderBottom: '1px solid #e9ecef',
    fontWeight: 600,
  },
  notificationList: {
    maxHeight: '400px',
    overflowY: 'auto' as const,
  },
  notificationItem: {
    padding: '12px 16px',
    borderBottom: '1px solid #f1f3f5',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  notificationItemUnread: {
    backgroundColor: '#e7f1ff',
  },
  notificationItemMessage: {
    fontSize: '14px',
    color: '#343a40',
    marginBottom: '4px',
  },
  notificationItemTimestamp: {
    fontSize: '12px',
    color: '#6c757d',
  },
  // --- Report Modal ---
  reportModalContent: {
    whiteSpace: 'pre-wrap' as const,
    lineHeight: 1.6,
    fontFamily: 'inherit',
    color: '#343a40',
  },
  // --- AI Copilot Modal ---
  copilotModalContent: {
    ...cardBase,
    width: '90%',
    maxWidth: '500px',
    height: '600px',
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    padding: 0,
    animation: 'slideInRight 0.3s ease-out forwards',
  },
  copilotHeader: {
    padding: '16px',
    borderBottom: '1px solid #e9ecef',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  copilotTitle: {
    fontSize: '18px',
    fontWeight: 600,
  },
  copilotStatusIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '4px 10px',
    borderRadius: '12px',
    backgroundColor: '#f8f9fa',
    border: '1px solid #e9ecef',
    fontSize: '14px',
    fontWeight: 500,
  },
  copilotStatusDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    transition: 'background-color 0.3s',
  },
  copilotTranscriptContainer: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column-reverse',
  },
  copilotTranscriptContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  copilotMessageBubble: {
    padding: '10px 14px',
    borderRadius: '18px',
    maxWidth: '80%',
    lineHeight: 1.5,
  },
  copilotUserMessage: {
    backgroundColor: '#007bff',
    color: 'white',
    alignSelf: 'flex-end',
    borderBottomRightRadius: '4px',
  },
  copilotModelMessage: {
    backgroundColor: '#e9ecef',
    color: '#212529',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: '4px',
  },
  copilotFooter: {
    borderTop: '1px solid #e9ecef',
    padding: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  copilotMicButton: {
    width: '70px',
    height: '70px',
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    transition: 'background-color 0.2s, box-shadow 0.2s, transform 0.2s',
  },
  copilotMicButtonActive: {
    backgroundColor: '#dc3545',
    color: 'white',
    boxShadow: '0 0 0 4px rgba(220, 53, 69, 0.4)',
  },
  copilotMicButtonInactive: {
    backgroundColor: '#28a745',
    color: 'white',
  },
  copilotThinkingIndicator: {
    background: 'linear-gradient(90deg, #007bff, #6610f2, #007bff)',
    backgroundSize: '200% 200%',
    animation: 'thinking 2s ease infinite',
  },

  // --- Competitor Analysis Screen ---
  competitorAnalysisLayout: {
      padding: '24px',
      maxWidth: '1000px',
      margin: '0 auto',
      display: 'flex',
      flexDirection: 'column',
      gap: '24px',
  },
  competitorInputContainer: {
      ...cardBase,
      padding: '24px',
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
  },
  competitorInputForm: {
      display: 'flex',
      gap: '12px',
  },
  competitorInput: {
      flex: 1,
      padding: '12px 16px',
      fontSize: '16px',
      border: '1px solid #ced4da',
      borderRadius: '8px',
  },
  competitorList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
  },
  competitorListItem: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '8px 12px',
      backgroundColor: '#f8f9fa',
      borderRadius: '6px',
      border: '1px solid #e9ecef',
  },
  competitorListItemUrl: {
      fontSize: '14px',
      color: '#495057',
      whiteSpace: 'nowrap' as const,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
  },
  competitorRemoveButton: {
      background: 'none',
      border: 'none',
      color: '#dc3545',
      cursor: 'pointer',
      fontSize: '18px',
      fontWeight: 'bold',
  },
  competitorResultsContainer: {
      ...cardBase,
      padding: '32px',
      minHeight: '300px',
  },
  competitorResultCard: {
      backgroundColor: '#f8f9fa',
      borderRadius: '12px',
      padding: '20px',
      border: '1px solid #e9ecef',
      marginBottom: '24px',
  },
};